import { Film, Sparkles } from 'lucide-react';
import { Finding } from '@frame-sense/types';

const mockFindings: Finding[] = [];

export default function Findings() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Editorial Findings</h1>
        <p className="text-sm text-muted-foreground">Autonomous analysis reports generated by the agentic cinema pipeline.</p>
      </div>

      {mockFindings.length === 0 ? (
        <div className="rounded-lg border bg-card p-12 text-center space-y-4">
          <div className="mx-auto w-12 h-12 rounded-full bg-studio-900 flex items-center justify-center text-muted-foreground">
            <Sparkles className="h-6 w-6 text-primary/80" />
          </div>
          <div className="space-y-1 max-w-sm mx-auto">
            <h3 className="font-semibold text-foreground text-sm">No editorial findings</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Run a telemetry analysis session or execute model evaluations on screenings to generate automated edit recommendations.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {mockFindings.map((finding) => (
            <div key={finding.id} className="rounded-lg border bg-card p-6 space-y-4 hover:border-primary/20 transition-colors">
              {/* Header */}
              <div className="flex items-start justify-between">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-foreground">{finding.title}</h3>
                    <span className={`text-xs px-2.5 py-0.5 rounded-full font-medium uppercase tracking-wider ${
                      finding.severity === 'high' 
                        ? 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
                        : 'bg-amber-500/10 text-amber-500 border border-amber-500/20'
                    }`}>
                      {finding.severity} priority
                    </span>
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Timestamp: {Math.floor(finding.timestampStart / 60)}m {finding.timestampStart % 60}s — {Math.floor(finding.timestampEnd / 60)}m {finding.timestampEnd % 60}s
                  </div>
                </div>
                <span className="text-xs text-muted-foreground">{new Date(finding.createdAt).toLocaleDateString()}</span>
              </div>

              {/* Description */}
              <p className="text-sm text-muted-foreground leading-relaxed">{finding.description}</p>

              {/* Actions Indicator */}
              <div className="flex gap-4 pt-2 border-t text-xs">
                <div className="flex items-center gap-1.5 text-muted-foreground">
                  <Film className="h-3.5 w-3.5" /> 1 Evidence Segment
                </div>
                <div className="flex items-center gap-1.5 text-primary">
                  <Sparkles className="h-3.5 w-3.5" /> 1 AI Edit Recommendation
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
