import { Film, Sparkles } from 'lucide-react';
import { Finding } from '@frame-sense/types';

const mockFindings: Finding[] = [
  {
    id: "f_1",
    screeningId: "sc_1",
    title: "Audience Attention Drop-off in Act 2 Climax",
    description: "Real-time attention levels dropped by 45% during the conversation between Marcus and Sophia. Dialogue timing drags; script analysis indicates repetitive dialogue beats.",
    severity: "high",
    timestampStart: 3420,
    timestampEnd: 3510,
    evidenceIds: ["ev_1"],
    recommendationIds: ["rec_1"],
    createdAt: "2026-08-28T16:05:00Z"
  },
  {
    id: "f_2",
    screeningId: "sc_2",
    title: "Confusion Spike on Character Entry",
    description: "Audience telemetry detected confusion markers at character entry frame. The script names this character as 'Dr. Evelyn' but no dialogue tags or visual descriptors establish the identity clearly in the cut.",
    severity: "medium",
    timestampStart: 18,
    timestampEnd: 24,
    evidenceIds: ["ev_2"],
    recommendationIds: ["rec_2"],
    createdAt: "2026-08-27T10:10:00Z"
  }
];

export default function Findings() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Editorial Findings</h1>
        <p className="text-sm text-muted-foreground">Autonomous analysis reports generated by the agentic cinema pipeline.</p>
      </div>

      <div className="space-y-4">
        {mockFindings.map((finding) => (
          <div key={finding.id} className="rounded-lg border bg-card p-6 space-y-4 hover:border-primary/20 transition-colors">
            {/* Header */}
            <div className="flex items-start justify-between">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-foreground">{finding.title}</h3>
                  <span className={`text-xs px-2.5 py-0.5 rounded-full font-medium uppercase tracking-wider ${
                    finding.severity === 'high' 
                      ? 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
                      : 'bg-amber-500/10 text-amber-500 border border-amber-500/20'
                  }`}>
                    {finding.severity} priority
                  </span>
                </div>
                <div className="text-xs text-muted-foreground">
                  Timestamp: {Math.floor(finding.timestampStart / 60)}m {finding.timestampStart % 60}s — {Math.floor(finding.timestampEnd / 60)}m {finding.timestampEnd % 60}s
                </div>
              </div>
              <span className="text-xs text-muted-foreground">{new Date(finding.createdAt).toLocaleDateString()}</span>
            </div>

            {/* Description */}
            <p className="text-sm text-muted-foreground leading-relaxed">{finding.description}</p>

            {/* Actions Indicator */}
            <div className="flex gap-4 pt-2 border-t text-xs">
              <div className="flex items-center gap-1.5 text-muted-foreground">
                <Film className="h-3.5 w-3.5" /> 1 Evidence Segment
              </div>
              <div className="flex items-center gap-1.5 text-primary">
                <Sparkles className="h-3.5 w-3.5" /> 1 AI Edit Recommendation
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
